version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pakistan
      - POSTGRES_DB=mlflowdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: mlflow-with-psycopg2:v2.20.3  # Your custom image
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pakistan
      - POSTGRES_DB=mlflowdb
    command: >
      mlflow server 
      --host 0.0.0.0 
      --port 5000 
      --backend-store-uri postgresql://admin:pakistan@postgres:5432/mlflowdb 
      --default-artifact-root file:///mlflow/artifacts
    volumes:
      - mlflow_artifacts:/mlflow/artifacts

volumes:
  postgres_data:
  mlflow_artifacts: