---
- name: Deploy MLflow
  hosts: all
  become: true
  vars:
    mlflow_repo: "https://github.com/jahangir842/mlflow.git"
    mlflow_dir: "/home/adminit/mlflow"
    mlflow_user: "adminit"

  tasks:
    - name: Ensure the adminit user exists
      ansible.builtin.user:
        name: "{{ mlflow_user }}"
        state: present

    - name: Ensure adminit user is added to docker group
      ansible.builtin.user:
        name: "{{ mlflow_user }}"
        groups: docker
        append: yes

    - name: Clone MLflow repository as adminit user
      ansible.builtin.git:
        repo: "{{ mlflow_repo }}"
        dest: "{{ mlflow_dir }}"
        update: yes
      become_user: "{{ mlflow_user }}"

