---
- name: Install required packages and Docker components
  hosts: all
  become: yes

  tasks:
    - name: Install EPEL release and essential packages
      ansible.builtin.dnf:
        name:
          - epel-release
          - git
          - nano
          - dnf-plugins-core
          - nfs-utils
        state: present

    - name: Install htop (optional, from EPEL)
      ansible.builtin.dnf:
        name: htop
        state: present
      ignore_errors: yes

    - name: Add Docker CE repository if not already present
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker CE and related packages
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Enable and start Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Download docker-compose binary
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/v2.36.0/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create symbolic link for docker-compose
      ansible.builtin.file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
