---
- name: Install required packages
  hosts: all
  become: yes
  tasks:
    - name: Install basic packages
      ansible.builtin.dnf:
        name:
          - git
          - nano
          - htop
          - epel-release
          - dnf-plugins-core
          - nfs-utils
        state: present
    - name: Add Docker CE repository
      ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo
    - name: Install Docker and related packages
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
    - name: Enable and start Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-compose
      ansible.builtin.et_url:
        url: "https://github.com/docker/compose/releases/download/v2.36.0/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
    - name: Create docker-compose symlink
      ansible.builtin.file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
