---
- name: Deploy MLflow
  hosts: all
  become: no
  become_user: adminit
  vars:
    mlflow_repo: "https://github.com/jahangir842/mlflow.git"
    mlflow_dir: "/home/adminit/mlflow"
  tasks:
    - name: Clone MLflow repository
      ansible.builtin.git:
        repo: "{{ mlflow_repo }}"
        dest: "{{ mlflow_dir }}"
        update: yes
    - name: Ensure docker-compose is up
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: "{{ mlflow_dir }}/docker_compose_installation"
